# Generated by Django 2.2.11 on 2021-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mlplatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='collater',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='data_abstract',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='data_field',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='data_interest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='data_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='dim_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='origin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_decision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_exparguments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_expcondition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_expdevice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_materialname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_platenumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='sample_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='submitter',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='submitter_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='submitter_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='data',
            name='submitter_organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
